import { FileImage, Info, Loader2, Upload, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import MediaPreview from "../components/MediaPreview.jsx";
import PageHeader from "../components/PageHeader.jsx";
import VerdictBadge from "../components/VerdictBadge.jsx";
import { detectFiles } from "../services/api.js";
import { normalizeResults } from "../utils/format.js";

const accepted = ".jpg,.jpeg,.png,.webp,.bmp,.tiff,.mp4,.mov,.avi,.mkv,.webm";

export default function ImageAnalysis() {
  const navigate = useNavigate();
  const [files, setFiles] = useState([]);
  const [isDragging, setIsDragging] = useState(false);
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState([]);
  const [error, setError] = useState("");

  const previews = useMemo(
    () =>
      files.map((file) => ({
        file,
        url: URL.createObjectURL(file),
        name: file.name,
        size: `${(file.size / (1024 * 1024)).toFixed(1)} MB`
      })),
    [files]
  );

  function addFiles(fileList) {
    const next = Array.from(fileList || []);
    setFiles(next);
    setResults([]);
    setError("");
  }

  async function submit() {
    if (!files.length) return;
    setLoading(true);
    setError("");
    try {
      const payload = await detectFiles(files);
      const normalized = normalizeResults(payload);
      setResults(normalized);
      if (normalized.length === 1) {
        navigate(`/scan-detail/${normalized[0].id}`);
      }
    } catch (err) {
      setError(err?.response?.data?.detail || "Detection API is not reachable. Start Django backend and try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <PageHeader
        icon={FileImage}
        title="Image Analysis"
        subtitle="Upload single or multiple images/videos — our CNN model detects deepfakes in seconds"
      />

      <div className="mb-6 rounded-2xl border border-guard-purple/30 bg-guard-purple/10 px-5 py-4 text-sm font-semibold text-white/80">
        <Info className="mr-2 inline text-guard-purple" size={18} />
        Results are generated by a CNN model trained on real and synthetic face datasets. Confidence between 40–70% is marked{" "}
        <span className="font-black text-guard-amber">Uncertain</span> for manual verification.
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr_430px]">
        <section>
          <label
            onDragOver={(event) => {
              event.preventDefault();
              setIsDragging(true);
            }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={(event) => {
              event.preventDefault();
              setIsDragging(false);
              addFiles(event.dataTransfer.files);
            }}
            className={`dashed-upload grid min-h-[420px] cursor-pointer place-items-center rounded-[28px] p-8 text-center transition ${
              isDragging ? "scale-[1.01] shadow-glow" : ""
            }`}
          >
            <input type="file" accept={accepted} multiple className="hidden" onChange={(event) => addFiles(event.target.files)} />
            <div>
              <div className="mx-auto mb-6 grid h-20 w-20 place-items-center rounded-3xl bg-white/10 text-white shadow-glow">
                <Upload size={38} />
              </div>
              <h3 className="text-2xl font-black">Drag & drop images here</h3>
              <p className="mt-2 text-white/70">
                or <span className="font-bold text-purple-300 underline">browse files</span> · JPEG, PNG, WebP up to 20 MB each
              </p>
              <div className="mt-8 grid grid-cols-3 gap-5 text-sm text-white/70">
                <div>
                  <p className="font-black text-white">Single image</p>
                  <p>Instant analysis</p>
                </div>
                <div>
                  <p className="font-black text-white">Batch upload</p>
                  <p>Up to 50 files</p>
                </div>
                <div>
                  <p className="font-black text-white">All formats</p>
                  <p>JPEG · PNG · WebP · Video</p>
                </div>
              </div>
            </div>
          </label>

          {files.length > 0 && (
            <div className="mt-6 glass rounded-3xl p-5">
              <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-lg font-black">{files.length} file{files.length > 1 ? "s" : ""} queued</p>
                  <p className="text-sm text-white/60">Preview and run CNN detection</p>
                </div>
                <button
                  disabled={loading}
                  onClick={submit}
                  className="inline-flex items-center justify-center gap-2 rounded-xl bg-guard-purple px-5 py-3 text-sm font-black text-white shadow-glow transition hover:scale-[1.02] disabled:opacity-60"
                >
                  {loading ? <Loader2 className="animate-spin" size={18} /> : <WandSparkles size={18} />}
                  {loading ? "Analyzing..." : "Run Detection"}
                </button>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                {previews.map((preview) => (
                  <div key={preview.url} className="rounded-2xl border border-white/10 bg-black/20 p-3">
                    <MediaPreview localUrl={preview.url} scan={{ original_filename: preview.name, size_label: preview.size }} overlay={false} />
                    <p className="mt-3 truncate text-sm font-bold">{preview.name}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {error && <div className="mt-5 rounded-2xl border border-red-400/40 bg-red-500/10 p-4 font-semibold text-red-200">{error}</div>}
          {results.length > 1 && (
            <div className="mt-6 glass rounded-3xl p-5">
              <h3 className="mb-4 text-xl font-black">Batch Results</h3>
              <div className="grid gap-3">
                {results.map((scan) => (
                  <button
                    key={scan.id}
                    onClick={() => navigate(`/scan-detail/${scan.id}`)}
                    className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4 text-left transition hover:border-guard-purple/60"
                  >
                    <span className="font-bold">{scan.original_filename}</span>
                    <span className="flex items-center gap-4">
                      <VerdictBadge verdict={scan.verdict} />
                      <span className="font-black">{scan.confidence}%</span>
                    </span>
                  </button>
                ))}
              </div>
            </div>
          )}
        </section>

        <aside className="space-y-6">
          <div className="glass rounded-3xl p-6">
            <h3 className="mb-6 text-lg font-black">How it works</h3>
            {[
              ["01", "Upload", "Drag & drop or browse JPEG/PNG/WebP images and videos up to 20 MB each"],
              ["02", "Detect", "CNN model extracts facial features and analyzes pixel-level patterns"],
              ["03", "Review", "See confidence score, verdict, and 4-signal breakdown instantly"],
              ["04", "Export", "Save to history and download a full detection report"]
            ].map(([step, title, text]) => (
              <div className="mb-6 flex gap-4" key={step}>
                <span className="text-sm font-black text-guard-purple">{step}</span>
                <div>
                  <p className="font-black">{title}</p>
                  <p className="text-sm leading-6 text-white/60">{text}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="glass rounded-3xl p-6">
            <h3 className="mb-5 text-sm font-black uppercase tracking-wider">Supported Formats</h3>
            <div className="flex flex-wrap gap-3">
              {[".jpeg", ".png", ".webp", ".bmp", ".tiff", ".mp4", ".mov"].map((item) => (
                <span key={item} className="rounded-lg bg-white/10 px-3 py-2 text-sm font-black text-white/70">
                  {item}
                </span>
              ))}
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
